name: ESP32-solo Arduino Libs CI

on:
  push:
    branches:
    - esp32-solo
    - esp32-solo-no-mac-crc
  pull_request:

jobs:

  build-libs:
    name: Build Arduino Libs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Build Arduino Libs
      run: bash ./build.sh
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: dist
