name: Remote Trigger

on: repository_dispatch

jobs:
  run:
    name: Dispatch Event
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Handle Event
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: bash ./tools/repository_dispatch.sh
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: dist
